### ISSUE TITLE
Example docstrings aren't rendered properly

### ISSUE THREAD

**Issue by bdice** [glotzerlab/coxeter#104]
### Description

The syntax for embedded examples isn't quite right. It needs a few changes to match standards for [Google style docstrings](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html):
1. Need a newline above the word "Example:" (one colon, not two).
2. Need to wrap input lines as if typing into an interpreter with line continuation `...`:
```python
>>> print('This is a long expression and it is split across',
... 'two lines. Note the periods at the beginning of this line.')
```
3. Some examples are a little lengthy and could be trimmed (do we need to get an incircle of a polygon _and_ compute its area?)
4. Write example code in a way that would pass through a formatter (e.g. black). For example, put spaces after commas in all lists of items:
```python
vertices = [[1, 1], [1, -1], [-1, -1], [-1, 1]]
# instead of
vertices=[[1,1],[1,-1],[-1,-1],[-1,1]]
```

 Here's what it looks like:

Incorrect syntax:

```python
class ConvexPolygon(Polygon):
    """A convex polygon.

    The polygon is embedded in 3-dimensions, so the normal
    vector determines which way is "up".

    Args:
        ...
    Example::
        >>> square = coxeter.shape_classes.ConvexPolygon([[1,1],[-1,-1],
                                                          [1,-1],[-1,1]])
        >>> square.area
        4.0
        >>> # ...continued
    """
```

Fixed syntax:

```python
class ConvexPolygon(Polygon):
    """A convex polygon.

    The polygon is embedded in 3-dimensions, so the normal
    vector determines which way is "up".

    Args:
        ...

    Example:
        >>> square = coxeter.shape_classes.ConvexPolygon(
        ...   [[1, 1], [-1, -1], [1, -1], [-1, 1]])
        >>> square.area
        4.0
        >>> # ...continued
    """
```

Incorrect output:
![image](https://user-images.githubusercontent.com/3943761/95512042-e0158200-097d-11eb-9f8f-cf358d7da900.png)

Fixed output:
![image](https://user-images.githubusercontent.com/3943761/95512216-2834a480-097e-11eb-86e7-f95172c12b45.png)

**Comment by vyasr** [comment]
Good catch on the formatting (1) and (2), I just started looking at the rendered formatting more and I'm seeing some of the places where there are issues. 

For (3) I agree that they're possible a little _too_ long, on the other hand I'd rather show too much than too little. Feel free to suggest which parts to prune, we can certainly cut some of the more esoteric properties.

Regarding (4) for better styling, I'm beginning to question my reliance on flake8 plugins again, in particular running pydocstyle directly pops up issues that running flake8 does not when I have flake8-docstrings installed. Having said that, even pydocstyle does not check for style in examples so I'm not sure there's a great way to check this programatically. We can certainly try to improve the existing examples, but I'd generally expect this to be a losing battle in the long haul.

**Comment by bdice** [comment]
@vyasr 
3. To clarify, the example I meant was showing properties of properties (area of incircle of square), not the square incircle and square area. The first-level examples are good. The second level is overly verbose. We are on the same page, I think.

4. I don’t know of a doctest formatter either. There is a script I found (will update this comment with the link) that applies black to doctests, but it only works if the syntax is a valid doctest to begin with.

**Comment by vyasr** [comment]
3. Yes we're on the same page then.
4. If that works then it seems reasonable to use. We run doctest anyway. Just depends on how well it works.
