### ISSUE TITLE
Add shape __repr__ methods

### ISSUE THREAD

**Issue by bdice** [glotzerlab/coxeter#126]
### Feature description

I would like to define `__repr__` methods for shape classes. I find this to be very useful when developing interactively.

The current behavior without these methods is:
```python
>>> coxeter.shapes.Sphere(3.0)
<coxeter.shapes.sphere.Sphere object at 0x7f5c869d6820>
```

### Proposed solution

I like to write `__repr__` methods to adhere to the invariant: `repr(eval(repr(obj))) == repr(obj)`. However, this would result in very long representations for shapes with many vertices.

I recommend that for shapes with "fixed" numbers of inputs (e.g. spheres just have `r`, ellipsoids just have `a, b, c`), the representation result should match the constructor signature, like:
```python
>>> ellipsoid = coxeter.shapes.Ellipsoid(1.0, 3.0, 2.0)
>>> ellipsoid
coxeter.shapes.Ellipsoid(a=1.0, b=3.0, c=2.0, center=(0, 0, 0))
```

For shapes with variable inputs (e.g. polygons), it would be fine to have something shorter like:
```python
>>> triangle = coxeter.shapes.Polygon([[-1, 0], [0, 1], [1, 0]])
>>> triangle
coxeter.shapes.Polygon(vertices=<3 vertices>)
```

**Comment by vyasr** [comment]
In cases with variable numbers of inputs, I recommend implementing `__repr__` by directly calling `repr(attr)` on the offending attributes. These attributes should be NumPy arrays essentially without exception, allowing us to rely on ndarray repr machinery to decide how much to print and allowing the user to configure this with `numpy.set_printoptions`. This should be documented somewhere.
