### ISSUE TITLE
"center" should mean Centroid (Center of Mass for shapes with uniform density)

### ISSUE THREAD

**Issue by bdice** [glotzerlab/coxeter#129]
Currently the `polyhedron.center` property appears to be defined as an average of the vertices. However, this does not always coincide with the shape's center of mass: https://bell0bytes.eu/centroid-convex/

https://github.com/glotzerlab/coxeter/blob/0b02755cb0cf9550f1ed3a94b5c9eeed21d25830/coxeter/shapes/polyhedron.py#L474-L477

I recommend the following:
- Clarify and define relevant properties (`center` = center of mass = centroid = barycenter) <sup>[1]</sup>
- The current behavior of `center` could be retained under another name, but the proper name for this is unclear to me

<sup>[1]</sup> I note that [Wikipedia says](https://en.wikipedia.org/wiki/Centroid) the center of mass, centroid, and barycenter are synonymous for shapes of uniform density:
> While in geometry the word barycenter is a synonym for centroid, in astrophysics and astronomy, the barycenter is the center of mass of two or more bodies that orbit each other. In physics, the center of mass is the arithmetic mean of all points weighted by the local density or specific weight. If a physical object has uniform density, its center of mass is the same as the centroid of its shape.

**Comment by vyasr** [comment]
Here are my thoughts
- The reason for the Wikipedia statement is that the centroid is the average of all _points_ in the figure, where points does not mean _vertices_ but literally all points. That would mean performing an integral and then dividing by the area, which is the calculation I was referring to in the discussion today when I said that for a constant density the two should coincide. I conveniently forgot that averaging over all points is in no way equal to averaging over the vertices.
- I don't think there is any issue with redefining the current behavior of center, although we should probably verify that before deciding whether to change it. In any case I would prefer to define a new property `com` or `center_of_mass` and move the existing definition of `center` to some more appropriate name. The final thing to do would be to decide which one `center` should be an alias for; I would also lean towards center of mass, but I think that should be assessed more carefully.
- Properties like moments of inertia etc should still be calculated relative to the origin of the coordinate system. We have discussed this before, and there are various reasons to prefer that over implicitly using the center of mass. If a user wants properties computed relative to the center of mass, they should set the com to the origin.

**Comment by bdice** [comment]
If we correctly calculate the center of mass, it should look similar (as an integral) to the inertia tensor computation. The inertia tensor currently isn't implemented for spheroshapes, meaning that we likely don't have a simple method to compute the center of mass, either. Here is a potential reference for computing these quantities for spheropolygons: https://journals.aps.org/pre/abstract/10.1103/PhysRevE.82.056713
