### ISSUE TITLE
Add factory method for Spheropolyhedra

### ISSUE THREAD

**Issue by b-butler** [glotzerlab/coxeter#13]
`sphero_shape` in `utils.py` should be a factory method for `SpheroConvexPolyhedra`.

**Comment by vyasr** [comment]
The behavior of `sphero_shape` was very specific and unintuitive. It performed an interpolation between a polyhedron and a sphere, but the choice of how to interpolate (I believe by volume) was arbitrary and would need to be better documented. I'm closing this issue as out of scope. If a need arises for a related feature in the future, it can be reimplemented using the new APIs (which transparently perform most of the calculations).
