### ISSUE TITLE
Points on the surface of shapes

### ISSUE THREAD

**Issue by tommy-waltmann** [glotzerlab/coxeter#136]
### Feature description

I would like the ability to get a set of points (ideally somewhat equally distributed) on the surface of the shapes.

### Proposed solution

I could access the points through a property called `points_on_surface`, or something similar to that

### Additional context

I am going to use this for the crystal structure prediction code that is in the beginning stages of development. If this feature is added, I may add a `coxeter` dependency to that package.

The feature would be used to get a set of grafting sites on the surface of the cores for grafting ligands onto.

**Comment by vyasr** [comment]
@Tobias-Dwyer do you think #137 can be directly applied to this? It seems like basically the same code, and I think what @tommy-waltmann wants is probably something your computing as an intermediate. I imagine that a function that samples angles and then calls the shape kernel should address this request.

**Comment by Tobias-Dwyer** [comment]
@vyasr as usual, right on the money. As long as you can feed in an array of angle values the shape kernel will compute the correct value of the shape kernel at those values of theta for @tommy-waltmann . For a polygon even spacing along the perimeter is easy.  You just have to make sure the distance along each point along each line segment is equal. But I'm not computing that as an intermediate. I am however breaking down the polygon into line segments which could probably be used to calculate what even spacing would be along the perimeter of the polygon.

**Comment by tommy-waltmann** [comment]
After looking closer at this, I don't think a property called `points_on_surface` will be necessary, I would just need the shape kernels to be implemented to do what I want.

@Tobias-Dwyer I would need the 3D shape kernels to be implemented though. If you want help implementing the 2D/3D kernels, I am happy to help.

Thanks everyone!

**Comment by Tobias-Dwyer** [comment]
@tommy-waltmann cool! Yeah for 3D I may need your help. I just need to find the general form to find where a vector projected from the origin intersects a face on a convex polyhedron and I should be good.

**Comment by vyasr** [comment]
@Tobias-Dwyer @tommy-waltmann I haven't checked on this in a while, have you made any progress towards getting this working for polyhedra?

**Comment by tommy-waltmann** [comment]
I haven't worked on these in 3D. I don't have research need for this like I thought I was going to, so I don't plan on doing this in 3D.

**Comment by Tobias-Dwyer** [comment]
I have not had a research purpose for this either and so have not implemented it yet... :/

**Comment by vyasr** [comment]
@tommy-waltmann @Tobias-Dwyer that's fine, but if there's no longer interest in this feature I'm going to close the issue. If neither of you need it then I don't see a need to keep this open, we can always reopen if someone wants it later.
