### ISSUE TITLE
Add high level documentation

### ISSUE THREAD

**Issue by evetion** [glotzerlab/coxeter#153]
Including a statement of need and maybe some other context. For example, this package does seem focused (but not limited) on the micro-scale and related sciences, but this is not mentioned anywhere.
 
There are guides for contributing and an API documentation, but not on other levels. You could take inspiration from the [four levels of documentation](https://documentation.divio.com/) and an implementation of that idea, such as the [Django documentation](https://docs.djangoproject.com/en/dev/#how-the-documentation-is-organized).

**Comment by vyasr** [comment]
@evetion I think the four levels of documentation are great. Until recently the documentation was almost exclusively reference guides (the API documentation), but right around when you were doing this review we merged in #151. I'm not sure if you saw that, but it added a series of examples that are essentially how-to guides for a number of use cases. Most of the nontrivial calculations in coxeter also include pretty extensive explanation as part of the docstrings as well (for example, see the [isoperimetric quotient of a polyhedron](https://coxeter.readthedocs.io/en/latest/package-shapes.html?highlight=inertia%20tensor#coxeter.shapes.ConvexPolyhedron.iq)). The last important piece is a tutorial, which I just added in #155 along with a new, more explicit statement of need (although not explicitly under that title) in the README. I also provide some more of the context that you suggested. Let me know what you think of these!
