### ISSUE TITLE
Add documentation for properties/methods inherited from the base shape classes

### ISSUE THREAD

**Issue by bdice** [glotzerlab/coxeter#154]
Searching for the term "isoperimetric quotient" does not show up with results for any of the classes where the property is inherited from the base class `Shape3D`. Only shapes with custom overrides show up (e.g. spheres always return exactly 1 and have a different docstring to indicate that). We need to add Sphinx documentation for properties/methods inherited from the base shape classes.

https://coxeter.readthedocs.io/en/latest/search.html?q=isoperimetric+quotient
https://github.com/glotzerlab/coxeter/blob/2414555de3f34b9fc46e81864852fef3fc21add5/coxeter/shapes/base_classes.py#L394

**Comment by vyasr** [comment]
This seems to be a problem with RTD search, not with the documentation itself. If I actually search for the text using my browser on the API documentation page, I find the property documented under all of the shapes that support it, even the ones where it is inherited.

**Comment by bdice** [comment]
@vyasr You’re right. I missed this earlier, I must have made a mistake when I did the same in-page search. I suppose this can be closed, unless we want to figure out what is wrong with the search…

**Comment by vyasr** [comment]
I don't know how much control we have over that, there's a decent chance we'll end up having to correspond with RTD folks to find the problem and that seems like more work than it's worth at this stage. I'm going to close this, we can reopen if someone runs into this again.
