### ISSUE TITLE
Unit tests fail

### ISSUE THREAD

**Issue by joaander** [glotzerlab/coxeter#158]
### Description

I get errors running `pytest`: https://github.com/glotzerlab/software/runs/4860075378?check_suite_focus=true#step:4:6026

### To reproduce

`python3 -m pytest -v ./coxeter/tests`

### Error output

```
square = coxeter.shapes.Polygon(vertices=[[-0.5, -0.5, 0.0], [-0.5, 0.5, 0.0], [0.5, 0.5, 0.0], [0.5, -0.5, 0.0]], normal=[0.0, 0.0, -1.0])

    def test_inertia_tensor(square):
        """Test the inertia tensor calculation."""
        square.center = (0, 0, 0)
        assert np.sum(square.inertia_tensor > 1e-6) == 1
        assert square.inertia_tensor[2, 2] == 1 / 6
    
        # Validate yz plane.
        rotation = rowan.from_axis_angle([0, 1, 0], np.pi / 2)
        rotated_verts = rowan.rotate(rotation, square.vertices)
        rotated_square = ConvexPolygon(rotated_verts)
        assert np.sum(rotated_square.inertia_tensor > 1e-6) == 1
>       assert rotated_square.inertia_tensor[0, 0] == 1 / 6
E       assert 0.1666666666666669 == 0.16666666666666666
E         +0.1666666666666669
E         -0.16666666666666666
```

### System configuration

Please complete the following information:

 - Operating System [e.g. macOS]: Linux, Ubuntu 20.04
 - Version of Python [e.g. 3.7]: 3.9.5
 - Version of coxeter [e.g. 1.0]: 0.6.1

### Cause of error

The failure results from the usage of == to compare floating point numbers. Floating point math is non-associative so different orders of operations produced by different Python builds or compiler optimizations lead to results that are rounded differently. Use `numpy.testing.assert_allclose` to perform relative checks with tolerances: https://numpy.org/doc/stable/reference/generated/numpy.testing.assert_allclose.html

**Comment by vyasr** [comment]
Thanks for finding this. After seeing this issue I searched through all our tests and was a little shocked to see how many of them were relying on floating point equality. Frankly I'm quite surprised that we haven't run into this problem before.

**Comment by joaander** [comment]
Thanks!
