### ISSUE TITLE
GSD Shape Spec for Polyhedra

### ISSUE THREAD

**Issue by tommy-waltmann** [glotzerlab/coxeter#167]
### Description

The `gsd_shape_spec` property of the `Polyhedron` class returns a dictionary with keys `type`, `vertices`, and `faces`. It should return a dictionary with keys `type`, `vertices`, and `indices` to be consistent with gsd.

### To reproduce

Make any polyhedron and print the `gsd_shape_spec` dictionary

### System configuration

Please complete the following information:

 - Operating System: macOS
 - Version of Python: 3.7.12
 - Version of coxeter: 0.6.1
 - Version of gsd: 2.4.2

**Comment by joaander** [comment]
Where is this completed? I don't see the commits on https://github.com/glotzerlab/coxeter/commits/master.

**Comment by janbridley** [comment]
#170
