### ISSUE TITLE
Tau defined as inverse?

### ISSUE THREAD

**Issue by bdice** [glotzerlab/coxeter#56]
### Description

It looks like the implementation of `tau` does not match its formula (one is the inverse of the other). The paper reference should be verified and this should be made consistent.

https://github.com/glotzerlab/euclid/blob/8f255d850def83348e24325fafe472b17c0008ee/euclid/shape_classes/convex_polyhedron.py#L39-L47

**Comment by vyasr** [comment]
This issue is now resolved [on next](https://github.com/glotzerlab/coxeter/commit/d72f42db74dccca67526512f6f6f448d72d05ff8).
