### ISSUE TITLE
Family523 S Documentation Corrections

### ISSUE THREAD

**Issue by j-proc** [glotzerlab/coxeter#87]
Seems that there are some discrepancies with the documentation of the [inverse/ golden ratio](https://coxeter.readthedocs.io/en/latest/package-shape-families.html#coxeter.shape_families.Family523.s). The text is taken for S while the value and attribute name are s. And only one of the attributes is shown. 

It might also be good to mention in the general class doc string that these Ss are based on the golden ratio. The current doc string is correct, but does rely on recognition of that form of the well known irrational.

**Comment by vyasr** [comment]
The issue for the individual docstrings is that the docstrings are above instead of below the variables in the source code. That's trivial to fix. Regarding the class docstring, I agree that it would be good to mention this in the class docstring.
