### ISSUE TITLE
Shape2D Abstract Properties (perimeter, planar moments of inertia)

### ISSUE THREAD

**Issue by bdice** [glotzerlab/coxeter#98]
### Feature description

I noticed that there are some abstract properties of `Shape3D` that are not mirrored for `Shape2D`.

`Shape3D` defines abstract volume, surface area, and inertia tensor properties.

`Shape2D` defines only area.

### Proposed solution

I suggest adding perimeter and planar moments of inertia to the `Shape2D` abstract properties.

I believe the perimeter property is not yet implemented for polygon or its convex/sphero variants.

**Comment by vyasr** [comment]
Reviewing what properties need to exist for various classes of shapes is what @Tobias-Dwyer is currently working on.
